### PR TITLE
Motion Profiling Test Code

### PR DESCRIPTION
**Pull request by sagarreddypatil**
This is the commit for the test code for motion profiling. Not completed yet. If you want, you can create another branch for this.

### CODE REVIEW

**Comment by NeerajMula** [comment]
What ru going to do with the values? You need to output them on something

**Comment by StealthySemicolon** [comment]
ilyyyyyyyyyyyyy buddy marry me ily

**Comment by StealthySemicolon** [comment]
that was not me

**Comment by StealthySemicolon** [comment]
that was jeeva and i just noticed

**Pull request merged**
